name: Integration Testing
on:
  pull_request:
    branches:    
      - gitaction_devops
jobs:
  stage-one:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build Packages
      run: |
        python3 --version
        cd torch_ort_inference
        python build.py
