name: Integration Testing
on:
  push:
    branches:    
      - gitaction_devops
      - github_actions_test
jobs:
  stage-one:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build Packages
      run: |
        python3 --version
        ls
        pip install onnxruntime-openvino
        cd torch_ort_inference
        python build.py
        cd dist
        ls
        cd ../demos/
        python bert_for_sequence_classification.py --input "This is a sample program"
